
[/Script/CommonUI.CommonUISettings]
CommonButtonAcceptKeyHandling=TriggerClick

[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=807778634EF487DB0026BFA8108B03D8
; DefaultPartsPool는 Project Settings > Data Manager Settings에서 등록하세요.
